# set server port
server:
  port: 8090  # 配置端口
#  ssl:
#    key-store: classpath:www.miaoc.top.pfx
#    key-store-password: S2Hy0Yz2
#    key-store-type: JKS
spring:
  datasource: # set database config
    url: jdbc:mysql://localhost:3306/formeal?useUnicode=true&characterEncoding=utf8&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234=Qwer
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  http:
    converters:
      preferred-json-mapper: fastjson       # Json转换器
  devtools:
    livereload:
      enabled : true
############################## mybatis-plus配置 开始 1 ##############################
mybatis-plus:
  mapper-locations: classpath*:com/miaoc/itools/*/mapper/mapping/*.xml
  type-aliases-package: com.xxxx.**.entity
  type-handlers-package: com.example.springbootdemo.typeHandler

  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true                                     # 配置的缓存的全局开关 ss
      lazyLoadingEnabled: true                                # 延时加载的开关
      multipleResultSetsEnabled: true                         # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印sql语句,调试用

############################## mybatis-plus配置 结束   ##############################


##====================================================分割线=============================================================##


message:
  accesskeyid: accesskeyid
  accesssecret: accesssecret
  signname: 微快递
  templatecode: templatecode
